### ISSUE TITLE
Update Project to meet Reccomended Community Standards

### ISSUE THREAD

**Issue by Akshu-on-github** [HackSquadDev/discord-python#33]
The [Community Insights](https://github.com/HackSquadDev/discord-python/community) tab shows that this project does not meet the recommended community standards. The aforementioned standards can be achieved by:
- [ ] Adding a CoC
- [ ] Adding Contributing Guidelines
- [ ] Adding Issue and PR templates

I'd like to contribute by adding the above documents

**Comment by madebylydia** [comment]
Hey there! Thank for opening this issue!

Please feel free to send us a PR with what you'd like to work on! This would be very appreciated to improve the community's experience with this repository!
